### ISSUE TITLE
Composer not installing package

### ISSUE THREAD

**Issue by slowas** [vitorf7/lv-loadmorepagination#1]
Hello, i have issue installing this package

  [InvalidArgumentException]
  Could not find package * at any version for your minimum-stability (stable). Check the package spelling or your min
  imum-stability

Please help

**Comment by vitorf7** [comment]
@slowas This seems to be that your project does not accept any package that does not have a minimum stability of dev. In your composer file normally there is an option:

```json
{
    "minimum-stability": "stable"
}
```
The reason for this was that I had created this package as a test for a previous company I worked for and was still thinking and still do think there may be some improvements that could be done as to how this works and I had left it as dev master only.

I have tagged this version as 0.1.0 so hopefully now if you install the package by running:

```bash
composer require vitorf7/lv-loadmorepagination
```

You should now be able as it is not only dev master. Can you let me know if this solves your problem. Sorry for the delay but did not see any email from Github
